@DotnetApiStarter.Api_HostAddress = http://localhost:5033

GET {{DotnetApiStarter.Api_HostAddress}}/weatherforecast/
Accept: application/json

### Create a New Product
POST {{DotnetApiStarter.Api_HostAddress}}/api/product
Content-Type: application/json
{
  "sku": "LAPTOP-001",
  "barcode": "laptop-001",
  "name": "Gaming Laptop",
  "description": "Gaming laptop",
  "unitprice": 45000,
  "reorderlevel": 5,
  "createdbyid": 1
}

### Get Products
GET {{DotnetApiStarter.Api_HostAddress}}/api/product

### Get Products by Page
GET {{DotnetApiStarter.Api_HostAddress}}/api/product/paged?pageNumber=1&pageSize=20

### Update a Product
PUT {{DotnetApiStarter.Api_HostAddress}}/api/product/1
Content-Type: application/json
{
  "id": 1,
  "sku": "LAPTOP-001x",
  "barcode": "laptop-001x",
  "name": "Gaming Laptop",
  "description": "Gaming laptop",
  "unitprice": 55000,
  "reorderlevel": 10,
  "modifiedbyid": 2
}

### Change Product Status
PATCH {{DotnetApiStarter.Api_HostAddress}}/api/product/1/status
Content-Type: application/json
{
  "id": 1,
  "isactive": false,
  "modifiedbyid": 2
}

### Delete a Product
DELETE {{DotnetApiStarter.Api_HostAddress}}/api/product/1